environment.mode: ${ENVIRONMENT_MODE:local}

server:
  port: ${SERVER_PORT:8080}
  servlet.context-path: ${SERVLET_CONTEXT_PATH:/template}
  tomcat:
    relaxed-path-chars: "[,]"
    relaxed-query-chars: "[,]"

spring:
  # profiles.include: json-logging
  datasource:
  #   url: ${DATASOURCE_URL}
  #   username: ${DATASOURCE_USERNAME}
  #   password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # default_schema: template
        enable_lazy_load_no_trans: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: ${LOG_QUERIES_SLOWER_THAN_MS:500}
  flyway:
    enabled: true
    schemas: template
    locations: classpath:db/migration
  web:
    resources.add-mappings: false
    locale: vi
    supported-locales: vi,en
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
    path: /docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

logbook:
  predicate:
    include:
      - path: /**
    exclude:
      - path: /template/docs/**
      - path: /template/swagger-ui/**
  strategy: ${LOGBOOK_STRATEGY:body-only-if-status-at-least}
  format:
    style: ${LOGBOOK_FORMAT_STYLE:json}

logging:
  level:
    org:
      hibernate:
        SQL_SLOW: trace
        SQL: ${LOG_LEVEL_HIBERNATE_SQL:info}
        orm.jdbc.bind: ${LOG_LEVEL_HIBERNATE_BIND:info}
      zalando.logbook: ${LOG_LEVEL_LOGBOOK:trace}

auth:
  non-authenticated-paths: /actuator/**,/docs/**,/swagger-ui/**
  cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:}
