server:
  port: ${SERVER_PORT:8080}
  servlet.context-path: ${SERVLET_CONTEXT_PATH:/template}
  tomcat:
    relaxed-path-chars: "[,]"
    relaxed-query-chars: "[,]"

spring:
  # profiles.include: json-logging
  # datasource:
  #   url: ${DATASOURCE_URL}
  #   username: ${DATASOURCE_USERNAME}
  #   password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # default_schema: template
        enable_lazy_load_no_trans: true
  flyway:
    enabled: true
    schemas: template
    locations: classpath:db/migration
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false
    locale: vi
    supported-locales: vi,en
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:5MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:5MB}

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
    path: /docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

environment.mode: local

logging:
  level:
    org:
      hibernate:
        SQL: ${HIBERNATE_SQL_LOG_LEVEL:INFO}
        orm.jdbc.bind: ${HIBERNATE_SQL_BINDING_LOG_LEVEL:INFO}
    com.tth.common.log:
      GetRequestLogger: ${GET_REQUEST_LOG_LEVEL:DEBUG}
      RequestResponseBodyLoggerAdvice: ${REQUEST_RESPONSE_BODY_LOG_LEVEL:DEBUG}

auth:
  non-authenticated-paths: ${NON_AUTHENTICATED_PATHS:/actuator/**,/docs/**,/swagger-ui/**}
  cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:}
